import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "@/components/providers/store.provider";
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <div className="flex min-h-screen bg-white">
            <Sidebar />
            <main className="flex-1 bg-background text-foreground">
              {children}
            </main>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
